language: python
python:
  - "3.5"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda env create -f env.yml 
  - conda activate edicer
  - pip install .

# command to run tests
script:
  - python edicer.py -q test/sample_cds_seqs.fasta -d test/test_references -k 21
  - python edicer.py -q test/sample_cds_seqs.fasta -d test/test_references -k 22
  - python edicer-summarise.py -i sample_cds_seqs_k21_output/run_summary.json sample_cds_seqs_k22_output/run_summary.json
